name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
env:
  FTP_HOST: ${{ secrets.FTP_SERVER }}
  FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
  FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
  LOCAL_FOLDER: "develop/release"
  REMOTE_FOLDER: "/dev.mixcore.org"
  DEPLOYMENT_FOLDER: "develop/deployment"

jobs:
  build:
    runs-on: windows-latest
    name: Build & Publish
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: 'develop'
        submodules: recursive
    - name: Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        submodules: recursive
    - name: Restore
      run: dotnet restore develop/Mixcore.sln
    - name: Build
      run: dotnet build develop/Mixcore.sln --no-restore
    - name: Publish
      run: |
        dotnet publish develop/src/applications/Mixcore/Mixcore.csproj -c Release --output develop/release --no-restore
    - name: Take app offline
      run: |
        cd $DEPLOYMENT_FOLDER
        bash $DEPLOYMENT_FOLDER/takeappoffline.sh
    - name: Deploy
      shell: bash
      run: |
        cd $LOCAL_FOLDER
        bash $DEPLOYMENT_FOLDER/deployment.sh
